project/gallery/urls.py
# coding: utf-8

from django.conf.urls import url

from gallery import views


urlpatterns = [
    url(r'^$', views.GalleryListView.as_view(), name='all-galleries'),
    url(r'^my-gallery/$', views.UserGalleryListView.as_view(), name='user-galleries'),
    url(r'^gallery/(?P<slug>[\w\-_]+)/$', views.GalleryDetailView.as_view(), name='show-gallery'),
    url(r'^gallery/(?P<slug>[\w\-_]+)/add-image/', views.AddImageCreateView.as_view(), name='add-image-to-gallery'),
    url(r'^add/$', views.GalleryCreateView.as_view(), name='add_gallery'),
]

project/project/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views
from filebrowser.sites import site as sitefilebrowser

from auth.decorators import anonymous_required

urlpatterns = [
    url(r'^admin/filebrowser/', include(sitefilebrowser.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url('^login/$', anonymous_required(views.login), name='login'),
    url('^logout/$', views.logout, {'next_page': '/'}, name='logout'),

    url(r'^', include('gallery.urls', namespace='gallery')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/admin/models.py
# Create your models here.

project/gallery/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from filebrowser.fields import FileBrowseField


class Gallery(models.Model):
    owner = models.ForeignKey(User, verbose_name=_(u'owner'))
    name = models.CharField(_(u'name'), max_length=100)
    slug = models.SlugField(_(u'slug'), max_length=100, unique=True)
    description = models.TextField(_(u'description'))

    class Meta:
        ordering = ('-pk',)
        verbose_name = _(u'gallery')
        verbose_name_plural = _(u'galleries')

    def __unicode__(self):
        return self.name


class Image(models.Model):
    gallery = models.ForeignKey(Gallery)
    image = FileBrowseField(_(u'image'), directory=lambda instance, filename: '/'.join([str(instance.gallery.slug), filename]), max_length=100, extensions=['.jpg', '.png', '.gif'], format='image')
    description = models.CharField(_(u'description'), max_length=255)

    class Meta:
        ordering = ('pk',)
        verbose_name = _(u'image')
        verbose_name_plural = _(u'images')

    def __unicode__(self):
        return self.image.name

project/gallery/forms.py
# coding: utf-8

import itertools

from django import forms
from django.utils.translation import ugettext_lazy as _
from slugify import slugify

from .models import Gallery, Image


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ('name', 'description')

    def save(self):
        if self.instance.pk:
            return super(GalleryForm, self).save()

        instance = super(GalleryForm, self).save(commit=False)

        max_length = Gallery._meta.get_field('slug').max_length
        instance.slug = orig = slugify(instance.name, only_ascii=True)[:max_length]

        for x in itertools.count(1):
            if not Gallery.objects.filter(slug=instance.slug).exists():
                break

            instance.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)

        instance.save()

        return instance


class ImageForm(forms.ModelForm):
    img = forms.ImageField(label=_(u'obrazek'))

    class Meta:
        model = Image
        fields = ('img', 'description',)

project/admin/views.py
# Create your views here.

project/gallery/views.py
# coding: utf-8

import os
import uuid

from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy, reverse
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from braces.views import SelectRelatedMixin, StaticContextMixin, FormMessagesMixin

from auth.mixins import LoginRequiredMixin
from .models import Gallery, Image
from .forms import GalleryForm, ImageForm
from .settings import GALLERY_DIRECTORY_BASE, GALLERY_DIRECTORY


class GallerySelectRelatedMixin(SelectRelatedMixin):
    select_related = (u'owner__username',)


class GalleryCreateView(LoginRequiredMixin,
                        GallerySelectRelatedMixin,
                        StaticContextMixin,
                        FormMessagesMixin,
                        CreateView,
                        ):
    model = Gallery
    form_class = GalleryForm
    success_url = reverse_lazy('gallery:user-galleries')
    form_valid_message = _(u'Galeria została dodana.')
    form_invalid_message = _(u'Wypełnij poprawnie formularz.')
    static_context = {
        'header': _(u'Nowa Galeria')
    }

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(GalleryCreateView, self).form_valid(form)


class GalleryListView(GallerySelectRelatedMixin,
                      StaticContextMixin,
                      ListView):
    model = Gallery
    paginate_by = 10
    static_context = {
        'header': _(u'Galerie')
    }


class UserGalleryListView(LoginRequiredMixin,
                          GalleryListView):
    static_context = {
        'header': _(u'Moje Galerie')
    }

    def get_queryset(self):
        return Gallery.objects.select_related().filter(owner=self.request.user)


class GalleryDetailView(LoginRequiredMixin,
                        GallerySelectRelatedMixin,
                        DetailView):
    model = Gallery

    def get_context_data(self, **kwargs):
        context_data = super(GalleryDetailView, self).get_context_data(**kwargs)
        context_data['header'] = self.object.name
        context_data['images'] = Image.objects.filter(gallery=self.object)
        return context_data


class AddImageCreateView(LoginRequiredMixin,
                         FormMessagesMixin,
                         CreateView):
    model = Image
    form_class = ImageForm
    form_valid_message = _(u'Obrazek został dodany do galerii')

    def get_fk_gallery(self):
        return get_object_or_404(Gallery, owner=self.request.user, slug=self.kwargs.get('slug'))

    def get_success_url(self):
        return reverse('gallery:show-gallery', args=[self.gallery.slug])

    def handle_uploaded_file(self, f):
        gallery_dir = os.path.join(GALLERY_DIRECTORY_BASE, GALLERY_DIRECTORY, self.gallery.slug)
        full_file_name = os.path.join(gallery_dir, "%s.%s" % (uuid.uuid4(), f.name.split('.')[-1].lower()))

        try:
            os.makedirs(os.path.join(settings.MEDIA_ROOT, gallery_dir))
        except:
            pass

        with open(os.path.join(settings.MEDIA_ROOT, full_file_name), 'wb+') as dest:
            for chunk in f.chunks():
                dest.write(chunk)

        return full_file_name

    def form_valid(self, form):
        self.gallery = self.get_fk_gallery()
        form.instance.gallery = self.gallery
        form.instance.image = self.handle_uploaded_file(self.request.FILES.get('img'))
        return super(AddImageCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super(AddImageCreateView, self).get_context_data(**kwargs)
        context_data['gallery'] = self.get_fk_gallery()
        context_data['header'] = _(u'Dodaj obrazek do galerii "%s"') % context_data['gallery']
        return context_data

project/gallery/templates/gallery/base.html
{% extends 'base.html' %}

{% load static %}


{% block base %}

    <div id="gallery">
        <h1>{{ header|default:'Header' }}</h1>
        {% block app %}{% endblock app %}
    </div>

{% endblock base %}


{% block app_css %}
    <link rel="stylesheet" href="{% static 'gallery/css/style.css' %}">
{% endblock app_css %}


{% block app_js %}

{% endblock %}

project/gallery/templates/gallery/gallery_detail.html
{% extends "gallery/base.html" %}


{% load static %}
{% load bootstrap3 %}
{% load thumbnail %}


{% block app %}

    {% if  object.owner == request.user %}
        <p class="text-right"><a href="{% url 'gallery:add-image-to-gallery' object.slug %}" class="btn btn-success">{% bootstrap_icon 'plus' %} Dodaj</a></p>
    {% endif %}

    {% if images %}
        <div class="row gallery">
            {% for i in images %}
                <div class="text-center col-md-3 col-xs-6 {% if forloop.counter0|divisibleby:4 %}clearfix clear{% endif %}">
                    {% thumbnail i.image  "x175" as im %}
                        <a href="{% get_media_prefix %}{{ i.image }}" title="{{ i.description }}" class="fancybox" rel="{{ object.slug }}">
                            <img src="{{ im.url }}" alt="{{ i.description }}" class="img-responsive">
                        </a>
                    {% endthumbnail %}

                    {% if i.description %}
                        <p>{{ i.description }}</p>
                    {% endif %}

                </div>
            {% endfor %}
        </div>
    {% else %}
        {% bootstrap_alert 'Ta galeria jest jeszcze pusta.' %}
    {% endif %}

{% endblock app %}

project/gallery/templates/gallery/gallery_form.html
{% extends "gallery/base.html" %}


{% load static %}
{% load bootstrap3 %}


{% block app %}

    <form action="" method="post">
        {% bootstrap_form form set_required=false %}
        {% csrf_token %}

        <div class="form-group">
            {% bootstrap_button "Zapisz" button_type="submit" %}
        </div>

    </form>

{% endblock app %}

project/gallery/templates/gallery/gallery_list.html
{% extends "gallery/base.html" %}


{% load static %}
{% load bootstrap3 %}


{% block app %}

    {% if request.user.is_authenticated %}
        <p class="text-right"><a href="{% url 'gallery:add_gallery' %}" class="btn btn-success">{% bootstrap_icon 'plus' %} Dodaj</a></p>
    {% endif %}

    {% if object_list %}
        <table class="table table-hover table-bordered table-responsive">
            <tr>
                <th>Nazwa</th>
                <th>Opis</th>
                <th>Właściciel</th>
                <th colspan="2"></th>
            </tr>
            {% for o in object_list %}
                <tr>
                    <td>{{ o.name }}</td>
                    <td>{{ o.description }}</td>
                    <td>{{ o.owner.username }}</td>
                    <td>
                        <a href="{% url 'gallery:show-gallery' o.slug %}" class="btn btn-xs btn-primary">{% bootstrap_icon 'eye-open' %} Zobacz</a>
                    </td>
                    <td>
                        {% if o.owner == request.user %}
                            <a href="{% url 'gallery:add-image-to-gallery' o.slug %}" class="btn btn-xs btn-default">{% bootstrap_icon 'edit' %} Dodaj zdjęcia</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        {% bootstrap_alert "Nie masz jescze galerii." dismissable=False %}
    {% endif %}


    {% if is_paginated %}<div class="text-center">{% bootstrap_pagination page_obj %}</div>{% endif %}

{% endblock app %}

project/gallery/templates/gallery/image_form.html
{% extends "gallery/base.html" %}


{% load static %}
{% load bootstrap3 %}


{% block app %}

    {% if form.errors %}
        {% bootstrap_alert "Wypełnij poprawnie formularz." alert_type='danger' %}
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        {% bootstrap_form form %}
        {% csrf_token %}

        <div class="form-group">
            {% bootstrap_button "Zapisz" button_type="submit" %}
        </div>

    </form>

{% endblock app %}

project/templates/_navigation.html
{% load bootstrap3 %}

<nav class="navbar navbar-default navbar-inverse">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'gallery:all-galleries' %}">{% bootstrap_icon 'picture' %} Galerie</a></li>
                {% if request.user.is_authenticated %}<li><a href="{% url 'gallery:user-galleries' %}">{% bootstrap_icon 'picture' %} Moje Galerie</a></li>{% endif %}
            </ul>

            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'logout' %}">{% bootstrap_icon "off" %} Wyloguj {{ request.user.username }}</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

project/templates/base.html
{% load static %}
{% load bootstrap3 %}


<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.css">

    {% block app_css %}{% endblock app_css %}

    <title>TestApp</title>
</head>
<body>
    {% block navigation %}
        {% include '_navigation.html' %}
    {% endblock navigation %}


    {% block messages %}
        {% if messages %}
            <div id="messages" class="container">{% bootstrap_messages %}</div>
        {% endif %}
    {% endblock messages %}


    {% block content %}
        <div class="container">
            {% block base %}{% endblock base %}
        </div>
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.pack.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".fancybox").fancybox();
        });
    </script>
</body>
</html>